## Basic Configuration
baseurl = "/"
languageCode = "en"

title = "Point Nine Four"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Tim Newans"
    title = "Point Nine Four"
    # description = "..."
    # authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    #github = "<username>"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "timnewans"
    twitter = "pointninefour"
    facebook = "pointninefour"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    email = "pointninefour@gmail.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Cricket"
    identifier = "cricket"
    weight = 200
    url = "/categories/cricket/"
